apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: default-issuer
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: default-issuer
    solvers:
    {{- if eq .Values.cloudProvider "aws" }}
    - dns01:
        route53:
          region: {{ .Values.aws.region }}
          {{- if .Values.aws.hostedZoneID }}
          hostedZoneID: {{ .Values.aws.hostedZoneID }}
          {{- end }}
    {{- else if eq .Values.cloudProvider "gcp" }}
    - dns01:
        cloudDNS:
          project: {{ .Values.gcp.project_id }}
        cnameStrategy: Follow
        podTemplate:
          spec:
            nodeSelector:
              kubernetes.io/os: linux
            tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
            containers:
              - name: cert-manager-acmesolver
                args:
                  - "--timeout=180"
    {{- end }}
